=== mvdh/INFSWA01/les2/xmlschema.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/xmlschema" xmlns:tns="http://www.example.org/xmlschema" elementFormDefault="qualified">
	<xs:element name="zaalvoetbal">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="wedstrijden">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="wedstrijd" maxOccurs="unbounded">
								<xs:complexType >
									<xs:sequence>
										<xs:element name="datum" type="xs:date" />
										<xs:element name="tijdstip">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="([0-1][0-9]|2[0-3]):[0-5][0-9]" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="uitslag">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="scorethuis" type="xs:nonNegativeInteger" />
													<xs:element name="scoreuit" type="xs:nonNegativeInteger" />									
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="wedstrijdnummer" type="xs:nonNegativeInteger" />
									<xs:attribute name="verenigingnummerthuis" type="xs:nonNegativeInteger" />
									<xs:attribute name="verenigingnummeruit" type="xs:nonNegativeInteger" />
									<xs:attribute name="teamnummerthuis" type="xs:nonNegativeInteger" />
									<xs:attribute name="teamnummeruit" type="xs:nonNegativeInteger" />
									<xs:attribute name="sporthalnummer" type="xs:nonNegativeInteger" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="verenigingen">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="vereniging"  maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="naam" type="xs:string" />
										<xs:element name="teams" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="team">
														<xs:complexType>
															<xs:attribute name="teamnummer" type="xs:nonNegativeInteger" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="verenigingnummer" type="xs:nonNegativeInteger" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="sporthallen">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="sporthal" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="naam" type="xs:string" />
										<xs:element name="telefoonnummer">
											<xs:simpleType>
												<xs:restriction base="xs:nonNegativeInteger">
													<xs:pattern value="[0-9]{10}" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="adres">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="postcode">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:pattern value="[0-9]{4}[A-Z]{2}" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="huisnummer" type="xs:positiveInteger" />
													<xs:element name="huisnummertoevoeging" type="xs:string" />
													<xs:element name="straatnaam" type="xs:string" />
													<xs:element name="plaats" type="xs:string" />	
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="sporthalnummer" type="xs:nonNegativeInteger" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="keyverenigingnummer">
			<xs:selector xpath="./verenigingen/vereniging" />
			<xs:field xpath="@verenigingnummer" />
		</xs:key>	
		<xs:key name="keyteamnummer">
			<xs:selector xpath="./verenigingen/vereniging/teams/team" />
			<xs:field xpath="@teamnummer"/>
		</xs:key>
		<xs:key name="keysporthalnummer">
			<xs:selector xpath="./sporthallen/sporthal"/>
			<xs:field xpath="@sporthalnummer"/>
		</xs:key>				
		<xs:keyref name="refverenigingnummerthuis" refer="keyverenigingnummer">
			<xs:selector xpath="./wedstrijden/wedstrijd"/>
			<xs:field xpath="@verenigingnummerthuis"/>
		</xs:keyref> 
		<xs:keyref name="refverenigingnummeruit" refer="keyverenigingnummer">
			<xs:selector xpath="./wedstrijden/wedstrijd"/>
			<xs:field xpath="@verenigingnummeruit"/>
		</xs:keyref> 
		<xs:keyref name="refteamnummerthuis" refer="keyteamnummer">
			<xs:selector xpath="./wedstrijden/wedstrijd"/>
			<xs:field xpath="@teamnummerthuis"/>
		</xs:keyref> 		
		<xs:keyref name="refteamnummeruit" refer="keyteamnummer">
			<xs:selector xpath="./wedstrijden/wedstrijd"/>
			<xs:field xpath="@teamnummeruit"/>
		</xs:keyref> 		
		<xs:keyref name="refsporthalnummer" refer="keysporthalnummer">
			<xs:selector xpath="./wedstrijden/wedstrijd"/>
			<xs:field xpath="@sporthalnummer"/>
		</xs:keyref> 		
	</xs:element>	
</xs:schema>

=== mvdh/INFSWA01/les2/test.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<zaalvoetbal 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="xmlschema.xsd">
	<wedstrijden>
		<!-- 
			TEST 0 - vereningingsnummerthuis bestaat niet  
		-->
		<wedstrijd 	wedstrijdnummer="1" verenigingnummerthuis="3" verenigingnummeruit="2" teamnummerthuis="1" teamnummeruit="2" sporthalnummer="1">
			
			<!-- 
				TEST 1 - Datum functie 
			-->
			<datum>2011-12-33</datum>
			<!-- 
				TEST 2 - reguliere expressie 
			-->
			<tijdstip>09:80</tijdstip>
			<uitslag>
				<!-- 
					TEST 3 - niet gebruiken van nonNegativeInteger  
				-->
				<scorethuis>-1</scorethuis>
				<scoreuit>1</scoreuit>
			</uitslag>
		</wedstrijd>
		<wedstrijd 	wedstrijdnummer="2" verenigingnummerthuis="2" verenigingnummeruit="1" teamnummerthuis="2" teamnummeruit="1" sporthalnummer="2">
			<datum>2011-16-07</datum>
			<tijdstip>21:00</tijdstip>
			<uitslag>
				<!-- 
					TEST 4 - weglaten element <scorethuis> 
				-->
				<scoreuit>1</scoreuit>
			</uitslag>
		</wedstrijd>	
	</wedstrijden>

	<verenigingen>
		<vereniging verenigingnummer="1">
			<naam>ZVOB</naam>
			<teams>
				<team teamnummer="1" verenigingnummer="1" />
				<team teamnummer="2" verenigingnummer="1" />
			</teams>
		</vereniging>
		<vereniging verenigingnummer="2">
			<naam>TOGR</naam>
			<teams>
				<team teamnummer="1" verenigingnummer="2" />
				<team teamnummer="2" verenigingnummer="2" />
			</teams>
		</vereniging>	
	</verenigingen>

	<sporthallen>
		<sporthal sporthalnummer="1">
			<naam>De Boogerd</naam>
			<!-- 
				TEST - telefoonnummer regex
			 -->
			<telefoonnummer>a201234567</telefoonnummer>
			<adres>
				<postcode>1234AB</postcode>
				<huisnummer>1</huisnummer>
				<huisnummertoevoeging></huisnummertoevoeging>
				<straatnaam>Kalverstraat</straatnaam>
				<plaats>Amsterdam</plaats>
			</adres>
		</sporthal>
		<sporthal sporthalnummer="2">
			<naam>De Ridderhal</naam>
			<telefoonnummer>0109876543</telefoonnummer>
			<adres>
				<!-- 
					TEST - Postcode regex
				 -->
				<postcode>ZY9876</postcode>
				<huisnummer>99</huisnummer>
				<!-- 
					TEST - Weglaten huisnummertoevoeging 
				-->
				<straatnaam>Coolsingel</straatnaam>
				<plaats>Rotterdam</plaats>
			</adres>
		</sporthal>	
	</sporthallen>
</zaalvoetbal>
